/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jbrod.parserpy.ui;

import com.jbrod.parserpy.app.analizer.MainClass;
import com.jbrod.parserpy.app.analizer.lexicon.Token;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge
 */
public class ReportViewer extends javax.swing.JPanel {

    private MainClass mainClass; 
    private DefaultTableModel tbModel; 
    
    /**
     * Creates new form ReportViewer
     */
    public ReportViewer() {
        initComponents();
        tbModel = (DefaultTableModel)tblReport.getModel();
    }

    public void setMainClass(MainClass mainClass) {
        this.mainClass = mainClass;
    }
    
    public void addReport(List<Token> lsToken){
       
        DefaultTableModel model = (DefaultTableModel) tblReport.getModel(); 
        model.setColumnCount(5);
        model.setRowCount(lsToken.size());
        //Tabla: Token | Patron | Lexema | Linea | Columna
        
        for (int i = 0; i < lsToken.size(); i++) {
            Token actual = lsToken.get(i);
           
            model.setValueAt(actual.getTokenType    (), i, 0); //Token
            model.setValueAt(actual.getPattern      (), i, 1); //Patron
            model.setValueAt(actual.getLexeme       (), i, 2); //Lexema
            model.setValueAt(actual.getRow          (), i, 3); //Linea
            model.setValueAt(actual.getColumn       (), i, 4); //Columna 
           
        }
        tblReport.removeAll();
            
        
    }
            

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Token", "Patron", "Lexema", "Linea", "Columna"
            }
        ));
        jScrollPane1.setViewportView(tblReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReport;
    // End of variables declaration//GEN-END:variables
}
