/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jbrod.parserpy.ui;

import com.jbrod.parserpy.app.analizer.MainClass;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.StyledEditorKit;

/**
 *
 * @author Jorge
 */
public class TextEditor extends javax.swing.JPanel {

    private MainClass mainClass; 
    
    /**
     * Creates new form TextEditor
     */
    public TextEditor() {
        initComponents();

    }

    public void setMainClass(MainClass mainClass) {
        this.mainClass = mainClass;
    }
    
    public String getInputToAnalize(){
        return textPaneCode.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textPaneCode = new javax.swing.JTextPane();

        jScrollPane1.setViewportView(textPaneCode);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane textPaneCode;
    // End of variables declaration//GEN-END:variables

    public void setText(String read) {
       textPaneCode.setText(read);
    }
}
