/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jbrod.analizer.ui;

import com.jbrod.analizer.Controller;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Jorge
 */
public class Codigo extends javax.swing.JPanel {

    private Controller controller; 
    private Tokens tokens; 
    
    /**
     * Creates new form Codigo
     */
    public Codigo(Controller controller) {
        initComponents();
        
        this.controller = controller; 
    }
    
    public void setTokens(Tokens tokens){
        this.tokens = tokens;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txpnCodigo = new javax.swing.JTextPane();
        btnAnalizarParse = new javax.swing.JButton();
        btnAbrirArchivo = new javax.swing.JButton();
        btnAnalizarLexer = new javax.swing.JButton();

        jScrollPane1.setViewportView(txpnCodigo);

        btnAnalizarParse.setText("Analizar (Parser)");
        btnAnalizarParse.setActionCommand("btnAnalizar");
        btnAnalizarParse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarParseActionPerformed(evt);
            }
        });

        btnAbrirArchivo.setText("Abrir archivo");
        btnAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirArchivoActionPerformed(evt);
            }
        });

        btnAnalizarLexer.setText("Analizar (Lexer)");
        btnAnalizarLexer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarLexerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnalizarParse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnalizarLexer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAbrirArchivo)
                        .addGap(0, 352, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnalizarParse)
                    .addComponent(btnAbrirArchivo)
                    .addComponent(btnAnalizarLexer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirArchivoActionPerformed
        // TODO add your handling code here:
        // Abre el explorador de archivos
                JFileChooser fileChooser = new JFileChooser();
                int seleccion = fileChooser.showOpenDialog(null);

                // Si el usuario seleccionó un archivo
                if (seleccion == JFileChooser.APPROVE_OPTION) {

                    // Obtiene el archivo seleccionado
                    File archivo = fileChooser.getSelectedFile();

                    // Lee el contenido del archivo
                    String contenido = "";
                    try {
                        contenido = new String(Files.readAllBytes(archivo.toPath()));
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }

                    // Establece el contenido del JTextPane
                    txpnCodigo.setText(contenido);
                }
    }//GEN-LAST:event_btnAbrirArchivoActionPerformed

    private void btnAnalizarParseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarParseActionPerformed
        try {
            // TODO add your handling code here:
            controller.analize(txpnCodigo.getText());
        } catch (IOException ex) {
            Logger.getLogger(Codigo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAnalizarParseActionPerformed

    private void btnAnalizarLexerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarLexerActionPerformed
        try {
            // TODO add your handling code here:
            controller.lex(txpnCodigo.getText());
            tokens.dibujarTokens();
        } catch (IOException ex) {
            Logger.getLogger(Codigo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAnalizarLexerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirArchivo;
    private javax.swing.JButton btnAnalizarLexer;
    private javax.swing.JButton btnAnalizarParse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txpnCodigo;
    // End of variables declaration//GEN-END:variables
}
