/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jbrod.analizer.ui;

import com.jbrod.analizer.Controller;
import com.jbrod.analizer.lexer.Token;
import com.jbrod.analizer.parser.tokens.SyntaxToken;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge
 */
public class Reportes extends javax.swing.JPanel {
    
    private Controller controller; 
    /**
     * Creates new form Reportes
     */
    public Reportes(Controller controller) {
        initComponents();
        this.controller = controller;
    }
    
    public void dibujarReportes(){
        LinkedList<SyntaxToken> lsToken = controller.getGeneralSyntax();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); 
       // model.setColumnCount(4  );
        model.setRowCount(lsToken.size());
        //Tabla: Sentencia | fila | columna | tipo | 
        
        System.out.println("size tokens repo: " + lsToken.size());
        for (int i = 0; i < lsToken.size(); i++) {
            SyntaxToken actual = lsToken.get(i);
           
            model.setValueAt(actual.getSentencia()  , i, 0); //Token
            model.setValueAt(actual.getFila()       , i, 1); //Patron
            model.setValueAt(actual.getColumna()    , i, 2); //Lexema
            model.setValueAt(actual.getTipo()       , i, 3); //Linea
           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sentencia", "Fila", "Columna", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
