/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jbrod.analizer.ui;

import com.jbrod.analizer.Controller;
import com.jbrod.analizer.lexer.Token;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge
 */
public class Tokens extends javax.swing.JPanel {

    private Controller controller; 
    /**
     * Creates new form Tokens
     */
    public Tokens(Controller controller) {
        initComponents();
        this.controller = controller; 
    }

    public void dibujarTokens(){
        
        LinkedList<Token> lsToken = controller.getTokens();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); 
        model.setColumnCount(5  );
        model.setRowCount(lsToken.size());
        //Tabla: Token | Patron | Lexema | Linea | Columna
        
        for (int i = 0; i < lsToken.size(); i++) {
            Token actual = lsToken.get(i);
           
            model.setValueAt(actual.getTokenType    (), i, 0); //Token
            model.setValueAt(actual.getPattern      (), i, 1); //Patron
            model.setValueAt(actual.getLexeme       (), i, 2); //Lexema
            model.setValueAt(actual.getRow          (), i, 3); //Linea
            model.setValueAt(actual.getColumn       (), i, 4); //Columna 
           
        }
        jTable1.removeAll();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Token", "Patron", "Lexema", "Linea", "Columna"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
